name: 'Build WordPress Archive'
description: 'Build a zip archive of your WordPress plugin & theme using GitHub Actions'
author: 'webshr'
branding:
  icon: 'archive'
  color: 'blue'
inputs:
  node-version:
    description: 'Node version'
    required: false
    default: 20
  install-composer:
    description: "Install Composer? Use 'true' to install all dependencies, 'no-dev' to exclude dev dependencies, or 'false' to skip."
    required: true
    default: no-dev
  npm-run-build:
    description: 'Run `npm run build`?'
    required: true
    default: false
  retention-days:
    description: 'Number of days to retain the artifact'
    required: false
    default: 30
  archive-name:
    description: 'Name of the zip archive'
    required: false
    default: ${{ github.event.repository.name }}
  upload-artifact:
    description: 'Upload the artifact?'
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      id: node-setup
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Generate zip archive
      id: generate-archive
      run: bash "${{ github.action_path }}/build.sh"
      shell: bash
      env:
        INSTALL_COMPOSER: ${{ inputs.install-composer }}
        NPM_RUN_BUILD: ${{ inputs.npm-run-build }}
        ARCHIVE_NAME: ${{ inputs.archive-name }}

    - name: Unzip the archive (prevents double zip problem)
      id: unzip-archive
      if: ${{ inputs.upload-artifact == 'true' }}
      run: |
        rm -rf dist-archive
        mkdir -p dist-archive
        unzip -q "${{ inputs.archive-name }}.zip" -d dist-archive
      shell: bash

    - name: Upload the archive as an artifact
      id: upload-archive-artifact
      if: ${{ inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.archive-name }}
        path: dist-archive
        retention-days: ${{ inputs.retention-days }}
